### PR TITLE
Fix for -var and -var-file parameters [semver:patch]

### PR DESCRIPTION
**Pull request by patrykkrawczyk**

### CODE REVIEW

**Comment by patrykkrawczyk** [comment]
@gmemstr @KyleTryon @aedifex please review

**Comment by KyleTryon** [comment]
@patrykkrawczyk Thanks for the submission. Could you describe the motivation behind this change? 

I believe we would also need to refer to this as a major change unfortunately as changing the name of the parameter will break a config for folks.

CCing the author of the orb @aedifex

**Comment by patrykkrawczyk** [comment]
@KyleTryon this is to fix https://github.com/CircleCI-Public/terraform-orb/issues/4
I changed the name of the parameter to resemble the name of the actual terraform parameter. To have the config unified.
About breaking config for folks - this config could not have worked before so I assume it will rather fix it.
Here's terraform docs for reference https://www.terraform.io/docs/commands/apply.html#var-file-foo

**Comment by KyleTryon** [comment]
@patrykkrawczyk Thank you! That is much appreciated. It may take us just a moment but we are doing a full review either this week or next week and we will merge and include this along with additional changes 👍. Thank you again

**Comment by gmemstr** [comment]
Resolved in #6

**Pull request closed without merging**
