### PR TITLE
feat: lock param on terraform plan (default to true)

### PR DESCRIPTION
**Pull request by VincentPerez**
Adding `lock` param on terraform plan (default to true)

I filed an issure here : https://github.com/CircleCI-Public/terraform-orb/issues/105

### CODE REVIEW

**Comment by henrahmagix** [comment]
@KyleTryon is it possible please to implement this PR? Currently, having terraform/plan run in every branch so we can review the output, makes any existing plan that's waiting to be applied stale, so it breaks our merging and applying flow. Being able to set `-lock=false` on PR branches would be extremely helpful ☺️ 

The changes seem to be correct to me =)

**Comment by KyleTryon** [comment]
> @KyleTryon is it possible please to implement this PR? Currently, having terraform/plan run in every branch so we can review the output, makes any existing plan that's waiting to be applied stale, so it breaks our merging and applying flow. Being able to set `-lock=false` on PR branches would be extremely helpful ☺️
> 
> The changes seem to be correct to me =)

Sorry. I am no longer a part of this organization.

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:daab6602bd753b523e83d07a13580628daab1486

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:8bb0ba44036b593990635ef08a2f629976ca04ed

**Review by marboledacci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:ef3478be3aa4b1d7e13c08ed91b067ea3c05b549

**Comment by henrahmagix** [comment]
Thanks so much @marboledacci!

**Pull request merged**
