### PR TITLE
Add option to run plan destroy to plan

### PR DESCRIPTION
**Pull request by marboledacci**
As requested on #113  I'm adding an option to run a plan for destroy.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:3c35bd5308c6f7356fb37bbe36f8350045bcb5ed

**Review by david-montano-circleci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:b95f40004d1371ec4a9bc957567f7578ba5bd1e5

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:b95f40004d1371ec4a9bc957567f7578ba5bd1e5

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=3.5.0

**Pull request merged**
