### PR TITLE
Add eval to path so it supports env

### LINKED ISSUE #94: Orb parameters don't work with CircleCI defined env vars
**Orb Version**
3.2.0

**Describe the bug**
When using the orb, I can't find a way to use an env variable defined in the CircleCI contexts inside an orb command. In my example I have the terraform modules in different paths based on environment, something like `env/qa` and `env/prod` and I define the `qa` and `prod` part in an ENV env variable in the contexts, e.g. `env/${ENV}`.

However I configure this path I get the error 

```
Path does not exist: ./env/${ENV}/
```
I tried using an absolute path as well, no luck.

**To Reproduce**

Use an environment variable in the `path` parameter in orb commands.

**Expected behavior**

I expect the orb to see and use the environment variables I set in CircleCI contexts or project settings.

### PR DESCRIPTION
**Pull request by marboledacci**
Resolves #94

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:077ab8fc9c6cbb2e55a09c349a6a3b3e08868cb1

**Review by david-montano-circleci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:bd238b1bd9dfd89a092afc27d38d46833d91e173

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:bd238b1bd9dfd89a092afc27d38d46833d91e173

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=3.4.0

**Pull request merged**
