### PR TITLE
[semver:major] 0.15.0 support

### LINKED ISSUE #37: Support Terraform 0.15.0
**Is your feature request related to a problem? Please describe.**
Some users would like to start using Terraform 0.15.0, which is not supported by the latest release of the Orb

**Describe the solution you'd like**
The two PRs being worked on should provide users with support for the latest version and features
https://github.com/CircleCI-Public/terraform-orb/pull/33
https://github.com/CircleCI-Public/terraform-orb/pull/35

### PR DESCRIPTION
**Pull request by KyleTryon**

### CODE REVIEW

**Review by punkdata — COMMENTED** [review]
I think we need a deeper dive into what was deprecated and why 0.15.0 breaks things. This will not fix the real issue which is how our orb is passing arguments to TF cli. The problem lies in the way the terraform is passing the args to the init cmd. See the list of init changes in the change log here. https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md

**Comment by EddM** [comment]
I started an attempt to bring the CLI commands up-to-date with 0.15.0 in #33, but it seems you're further along than I am!

Would it be possible to publish a version of the orb that locks terraform at a version < 0.15.0, for now?

**Comment by ppferrari** [comment]
It would be great to have also the option to pass a different tag version for the terraform image as a parameter to the jobs.

**Comment by punkdata** [comment]
> It would be great to have also the option to pass a different tag version for the terraform image as a parameter to the jobs.

@PPFerrari @Eddm The default will be pinned to TF ver 0.14.10 for now check PR https://github.com/CircleCI-Public/terraform-orb/pull/34 and thanks for the feedback

**Comment by arthurio** [comment]
Hey there 👋🏻 Thanks for working on supporting 0.15, is it still something you are looking at? Should we make a separate PR for just 0.15 support without the enhancements to get things moving faster?

**Comment by arthurio** [comment]
@KyleTryon Can you tell me if you have any ETA on 0.15 support or at least if you are still working on it? I don't want to sound pushy or anything, just trying to figure out what is the best path for me to get unblocked (fork, separate PR, etc.).

**Comment by KyleTryon** [comment]
> @KyleTryon Can you tell me if you have any ETA on 0.15 support or at least if you are still working on it? I don't want to sound pushy or anything, just trying to figure out what is the best path for me to get unblocked (fork, separate PR, etc.).

Hello @arthurio 
The general consensus is that this orb could probably use more attention than what is in this PR to improve its usage. We are internally discussing rebuilding the orb from the ground up for a next version but currently lack the resources in the short term and I am not a master of terraform. I will speak with a few other folks who may be able to assist.

My assumption right now is we will be able to pick this up at the end of July (for a full rebuild) or early August for full transparency for where I am currently.

I am going to close this PR, but if you are interested in sending in a patch/minor PR I am more than happy to help get that change out.

As @punkdata pointed out, it seems more than just a version change but perhaps some parameters have changed (actually resulting in a major change anyway more than likely.).

We will also need to address Terraform 1.0.0 is officially released now: https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability

**Comment by punkdata** [comment]
Changes are being implemented in PR #46

**Pull request closed without merging**
