### PR TITLE
fix: add workspace parameter to validate

### PR DESCRIPTION
**Pull request by KyleTryon**
# Fixes 
- #55

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:a34d07519458068cc385c5dd026321aea346fe3b

**Review by Jaryt — APPROVED** [review]
lgtm!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:81c0aad8108de96562958ddaec486d31ba8da9a6

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=dev:81c0aad8108de96562958ddaec486d31ba8da9a6

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/terraform?version=3.1.0

**Pull request merged**
