### PR TITLE
[semver:patch] update install.yml sudo use

### LINKED ISSUE #23: Command terraform/install requires sudo, which is missing
**Orb Version**

1.2.0

**Describe the bug**

When using the terraform/install command to install a specific version of Terraform, the command fails executing `sudo mv terraform /usr/local/bin` with the following error: `/bin/sh: sudo: not found`.

**To Reproduce**

1. Use the `circleci/terraform@1.2.0` orb in your pipeline
2. Setup a job running with executor `terraform/default`
3. Add the `terraform/install` command to the job
4. Schedule a pipeline run
5. Observer your terraform job failing at the `terraform/install` step

**Expected behavior**

_EITHER_ The [`terraform/default` execution environment](https://hub.docker.com/r/hashicorp/terraform) is configured to support the execution of the `terraform/install` command.

_OR_ The [orb documentation](https://circleci.com/developer/orbs/orb/circleci/terraform#commands-install) mentions the additional steps required to prepare the execution environment for the execution of the `terraform/install` command. 

**Additional context**

```
version: 2.1

orbs:
  terraform: circleci/terraform@1.2.0

jobs:
  # Terraform
  deploy_infrastructure:
    executor: terraform/default
    working_directory: ~/my-repository/infrastructure
    steps:
      - attach_workspace:
          name: Attach workplace from previous job(s)
          at: ~/my-repository
      - terraform/install:
          terraform_version: 0.13.5
```

### PR DESCRIPTION
**Pull request by dsayling**
sudo is not always available or necessary, so check and set an envvar
fix #23

### CODE REVIEW

**Comment by dsayling** [comment]
@KyleTryon you'll have to help me fix the creds here....

```
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

Please see https://www.terraform.io/docs/language/settings/backends/s3.html
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by dsayling** [comment]
Also, there's a warning we'll probably want to fix soon too

```

Warning: Interpolation-only expressions are deprecated

  on src/infra/main.tf line 40, in output "instance_ips":
  40:   value = ["${aws_instance.example.*.public_ip}"]

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

**Review by gmemstr — APPROVED** [review]
Approving, pending test results.

**Comment by dsayling** [comment]
@aedifex Can you help get these creds fixed?

**Comment by bushong1** [comment]
Would love to see this fix taken up.

**Pull request merged**
